# Generated by Django 3.1.3 on 2021-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210630_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
