# Generated by Django 3.2.4 on 2021-06-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210629_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
