# Generated by Django 3.2.4 on 2021-06-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactivate', 'inactivate')], default=False, max_length=30),
        ),
    ]
