# Generated by Django 3.1.3 on 2021-06-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default=False, max_length=30),
        ),
    ]
