# Generated by Django 3.1.3 on 2021-07-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_review_product'),
        ('home', '0008_brand'),
    ]

    operations = [
    ]
