# Generated by Django 3.1.3 on 2021-07-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_merge_20210707_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactivate', 'inactivate')], max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactivate', 'inactivate')], default=False, max_length=30),
        ),
    ]
