# Generated by Django 3.1.3 on 2021-07-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cart_total'),
        ('home', '0012_cart'),
    ]

    operations = [
    ]
